version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Use bind mount for live code reloading in dev
    volumes:
      - .:/app
    # Uncomment this line if you use FastAPI's autoreload (only for dev)
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
